# Generated by Django 3.2.4 on 2021-06-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0003_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='site',
        ),
    ]
